#!/bin/bash

read -p "Name: " name
read -p "Type (p/n/d/g): " type
read -p "Division: " div
echo -n "Password: " 
read -s password
echo
java -classpath ".:../src:../lib/sqlite-jdbc-3.7.15-M1.jar" usertool "$type" "$name" "$div" "$password"
id=$?

rm client_* client.tar.gz
echo "Creating client certificate..."
keytool -keystore client_trust.store -alias client -import -file ca.crt -storepass password -dname "CN=$id" -noprompt
keytool -keystore client_key.store -alias client -genkey -storepass password -keypass password -dname "CN=$id"
keytool -keystore client_key.store -alias client -certreq -keyalg rsa -file client.csr -storepass password
openssl x509 -CA ca.crt -CAkey ca.key -req -in client.csr -out client.crt -set_serial 1
keytool -keystore client_key.store -alias ca -import -file ca.crt -storepass password -noprompt
keytool -keystore client_key.store -alias client -import -file client.crt -storepass password -noprompt
rm client.csr
tar -zcf client.tar.gz client_key.store client_trust.store
echo "all done"

