#!/bin/bash
read -p "Name: " name
read -p "Type (p/n/d): " type
read -p "Division: " div
echo -n "Password: " 
read -s password
echo
java -classpath ".:../src:../lib/sqlite-jdbc-3.7.15-M1.jar" usertool $type $name $div $password
