#!/bin/bash
echo "Creating certificate authority..."
openssl genrsa -out ca.key
openssl req -new -key ca.key -out ca.csr -days 3650 -subj '/C=SE/ST=Skane/L=Lund/CN=root'
openssl x509 -req -signkey ca.key -in ca.csr -out ca.crt
rm ca.csr

echo "Creating server certificate..."
keytool -keystore server_trust.store -alias server -import -file ca.crt -storepass password -dname "CN=server" -noprompt
keytool -keystore server_key.store -alias server -genkey -storepass password -keypass password -dname "CN=server"
keytool -keystore server_key.store -alias server -certreq -keyalg rsa -file server.csr -storepass password
openssl x509 -CA ca.crt -CAkey ca.key -req -in server.csr -out server.crt -set_serial 1
keytool -keystore server_key.store -alias ca -import -file ca.crt -storepass password -noprompt
keytool -keystore server_key.store -alias server -import -file server.crt -storepass password -noprompt
rm server.csr
